spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: guru
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql
security:
  oauth2:
    resource:
#      token-info-uri: http://localhost:9090/oauth/check_token
      jwt:
        key-value: -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyZcyVVYkFatvAL4233m7
          9pKGJNp3a4reCEu0E5ViAbWLMPYFl2Y2iiga8WYYn7j8geh6miSIp5vhD0XTj9Jt
          ivT8Qc8+BFB6rCQccYA/CxNO28q483FyT3XhcK4qmcyawvL9rvgWiXAn91LAVowb
          +HdwxaPYSht58VXbGzXLQZNcmVnr5haThJn2f/BfjUphpk1TyxWijFg7w68hqRW2
          himTkqjJFDHpz9QLvAmzv79up02b+vql0N5HxAnHpFclAAZUmLlIuIfcNN2gF86f
          /cYM7utJOnNfWzylf2vTbEA+WI4f85/oWB2Fht7Zq0QIWfrHfhcGfRmqTBQnIyud
          gQIDAQAB
          -----END PUBLIC KEY-----
    client:
      clientId: nistruct
      clientSecret: nistruct@mk2019!
